=== mouhamadmourtada/xml/storage/cinemaDTD.dtd
<!ELEMENT cinema (film+)>
<!ELEMENT film (titre | genre | duree | realisateur | acteurs | annee | langue | synopsis | notePresse | noteSpectateur | horaires)*>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT duree (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>
<!ELEMENT acteurs (acteur+)>
<!ELEMENT acteur (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT langue (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT notePresse (#PCDATA)>
<!ATTLIST notePresse valeur CDATA #REQUIRED>
<!ATTLIST notePresse base CDATA #REQUIRED>
<!ELEMENT noteSpectateur (#PCDATA)>
<!ATTLIST noteSpectateur valeur CDATA #REQUIRED> 
<!ATTLIST noteSpectateur base CDATA #REQUIRED>
<!ELEMENT horaires (horaire+)>
<!ELEMENT horaire (jour+, heure+)>
<!ELEMENT jour EMPTY>
<!ATTLIST jour valeur (LUNDI|MARDI|MERCREDI|JEUDI|VENDREDI|SAMEDI|DIMANCHE) #REQUIRED>
<!ELEMENT heure (#PCDATA)>

=== mouhamadmourtada/xml/storage/cinema2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cinema SYSTEM "cinemaDTD.dtd">
<cinema>

	<film id_film="film_1">
		<titre>Les Brigades du Tigre</titre>
		<duree>120</duree>
		<genre>Comédie</genre>
		<realisateur>Jean-Pierre Melville</realisateur>
		<acteurs>
			<acteur>Amélie Poulain</acteur>
			<acteur>Jean-Pierre Melville</acteur>
			<acteur>Michel Bouquet</acteur>
			<acteur>Jean-Pierre Darroussin</acteur>
		</acteurs>
		<annee>1962</annee>
		<langue>Français</langue>
        <notePresse valeur="3" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        

		<synopsis>Amélie Poulain, une actrice de la comédie française, est un jour à la recherche d'un nouveau rôle. Mais elle est déjà occupée à la tâche de la part de l'agente du service de police, qui doit déterminer la mort de son client, un homme de lettres.</synopsis>
		<horaires>

            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>

            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>

            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>

			
        </horaires>
    </film>
    <!-- les 8 salpartd diango unchained, titanic, avengers, fight club,  old boy, john wick, avatar, dune-->
    

    <film id_film="film_2">
        <titre>Les 8 salopards</titre>
        <duree>120</duree>
        <genre>Comédie</genre>
        <realisateur>Quentin Tarantino</realisateur>
        <acteurs>
            <acteur>Samuel L. Jackson</acteur>
            <acteur>Quentin Tarantino</acteur>
            <acteur>Tim Roth</acteur>
            <acteur>Michael Madsen</acteur>
        </acteurs>
        <annee>2015</annee>
        <langue>Anglais</langue>
        <notePresse valeur="4" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        <synopsis>
            Huit chasseurs de primes sont bloqués dans un refuge de montagne par une tempête de neige. Ils réalisent qu'ils ont été piégés par une conspiration et qu'ils devront peut-être se battre pour leur survie.
        </synopsis>
        <horaires>
            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MARDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MERCREDI"/>
                <heure>14h00</heure>
            </horaire>
        </horaires>
    </film>

    <film id_film="film_3">
        <titre>Django Unchained</titre>
        <duree>120</duree>
        <genre>Comédie</genre>
        <realisateur>Quentin Tarantino</realisateur>
        <acteurs>
            <acteur>Samuel L. Jackson</acteur>
            <acteur>Quentin Tarantino</acteur>
            <acteur>Tim Roth</acteur>
            <acteur>Michael Madsen</acteur>
        </acteurs>
        <annee>2012</annee>
        <langue>Anglais</langue>
        <notePresse valeur="4" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        <synopsis>
            Huit chasseurs de primes sont bloqués dans un refuge de montagne par une tempête de neige. Ils réalisent qu'ils ont été piégés par une conspiration et qu'ils devront peut-être se battre pour leur survie.
        </synopsis>
        <horaires>
            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MARDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MERCREDI"/>
                <heure>14h00</heure>
            </horaire>
        </horaires>
    </film>

    <film id_film="film_4">
        <titre>Titanic</titre>
        <duree>120</duree>
        <genre>Comédie</genre>
        <realisateur>pas quantin</realisateur>
        <acteurs>
            <acteur>Samuel L. Jackson</acteur>
            <acteur>Quentin Tarantino</acteur>
            <acteur>Tim Roth</acteur>
            <acteur>Michael Madsen</acteur>
        </acteurs>
        <annee>2012</annee>
        <langue>Anglais</langue>
        <notePresse valeur="4" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        <synopsis>
            Huit chasseurs de primes sont bloqués dans un refuge de montagne par une tempête de neige. Ils réalisent qu'ils ont été piégés par une conspiration et qu'ils devront peut-être se battre pour leur survie.
        </synopsis>
        <horaires>
            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MARDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MERCREDI"/>
                <heure>14h00</heure>
            </horaire>
        </horaires>

    </film>

    <film id_film="film_5">
        <titre>Avengers</titre>
        <duree>120</duree>
        <genre>Comédie</genre>
        <realisateur>Quentin Tarantino</realisateur>
        <acteurs>
            <acteur>Samuel L. Jackson</acteur>
            <acteur>Quentin Tarantino</acteur>
            <acteur>Tim Roth</acteur>
            <acteur>Michael Madsen</acteur>
        </acteurs>
        <annee>2012</annee>
        <langue>Anglais</langue>
        <notePresse valeur="4" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        <synopsis>
            Huit chasseurs de primes sont bloqués dans un refuge de montagne par une tempête de neige. Ils réalisent qu'ils ont été piégés par une conspiration et qu'ils devront peut-être se battre pour leur survie.
        </synopsis>
        <horaires>
            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MARDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MERCREDI"/>
                <heure>14h00</heure>
            </horaire>
        </horaires>
    </film>

    <film id_film="film_6">
        <titre>Fight Club</titre>
        <duree>120</duree>
        <genre>Comédie</genre>
        <realisateur>Quentin Tarantino</realisateur>
        <acteurs>
            <acteur>Samuel L. Jackson</acteur>
            <acteur>Quentin Tarantino</acteur>
            <acteur>Tim Roth</acteur>
            <acteur>Michael Madsen</acteur>
        </acteurs>
        <annee>2012</annee>
        <langue>Anglais</langue>
        <notePresse valeur="4" base="5"/>
        <noteSpectateur valeur="4" base="5"/>
        <synopsis>
            Huit chasseurs de primes sont bloqués dans un refuge de montagne par une tempête de neige. Ils réalisent qu'ils ont été piégés par une conspiration et qu'ils devront peut-être se battre pour leur survie.
        </synopsis>
        <horaires>
            <horaire>
                <jour valeur="LUNDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MARDI"/>
                <heure>14h00</heure>
            </horaire>
            <horaire>
                <jour valeur="MERCREDI"/>
                <heure>14h00</heure>
            </horaire>
        </horaires>
    </film>



<film id_film="film_10"><titre>Test</titre><annee>2021</annee><duree>120</duree><realisateur>Moi</realisateur><genre>Action</genre><langue/><synopsis/><notePresse valeur="5" base="10"/><noteSpectateur valeur="5" base="10"/><acteurs><acteur>Moi</acteur><acteur>Toi</acteur><acteur>Lui</acteur></acteurs><horaires><horaire><jour valeur="LUNDI"/><jour valeur="MARDI"/><heure>10h</heure><heure>14h</heure></horaire><horaire><jour valeur="MERCREDI"/><jour valeur="JEUDI"/><heure>12h</heure><heure>16h</heure></horaire></horaires></film>
<film id_film="film_11"><titre>Test</titre><annee>2021</annee><duree>120</duree><realisateur>Moi</realisateur><genre>Action</genre><langue/><synopsis/><notePresse valeur="5" base="10"/><noteSpectateur valeur="5" base="10"/><acteurs><acteur>Moi</acteur><acteur>Toi</acteur><acteur>Lui</acteur></acteurs><horaires><horaire><jour valeur="LUNDI"/><jour valeur="MARDI"/><heure>10h</heure><heure>14h</heure></horaire><horaire><jour valeur="MERCREDI"/><jour valeur="JEUDI"/><heure>12h</heure><heure>16h</heure></horaire></horaires></film>

    
</cinema>
